


/*
 * Kieran Bates
 * September 19, 2019
 * This program calculates the average of four marks, rounds the output to 
 * two decimal places and displays the answer in a label
 */

import java.awt.event.KeyEvent; //Import the package that supports buttons

public class averageCalculatorUi extends javax.swing.JFrame {

    public averageCalculatorUi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        mark1 = new javax.swing.JLabel();
        mark2 = new javax.swing.JLabel();
        mark3 = new javax.swing.JLabel();
        mark4 = new javax.swing.JLabel();
        mark1Input = new javax.swing.JTextField();
        mark2Input = new javax.swing.JTextField();
        mark3Input = new javax.swing.JTextField();
        mark4Input = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        subtitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Lao UI", 0, 18)); // NOI18N
        Title.setText("Average Mark Calculator");

        mark1.setText("Mark 1");

        mark2.setText("Mark 2");

        mark3.setText("Mark 3");

        mark4.setText("Mark 4");

        mark1Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark1InputActionPerformed(evt);
            }
        });

        mark2Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark2InputActionPerformed(evt);
            }
        });

        mark4Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mark4InputActionPerformed(evt);
            }
        });

        calculateButton.setFont(new java.awt.Font("Lao UI", 0, 11)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        output.setEditable(false);
        output.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        output.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputActionPerformed(evt);
            }
        });

        subtitle.setText("Please enter your best four final grades.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(calculateButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtitle)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mark3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mark4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mark1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mark2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(mark4Input, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                        .addComponent(mark1Input)
                                        .addComponent(mark2Input)
                                        .addComponent(mark3Input)))
                                .addComponent(Title))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark1)
                    .addComponent(mark1Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark2)
                    .addComponent(mark2Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark3)
                    .addComponent(mark3Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mark4)
                    .addComponent(mark4Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calculateButton)
                .addGap(18, 18, 18)
                .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        double mark1; //Declare variable for the first mark
        double mark2; //Declare variable for the second mark
        double mark3; //Declare variable for the third mark
        double mark4; //Declare variable for the fourth mark
        double average; //Declare variable for the average mark
        double roundedAverage; //Declare variable for the average mark rounded to two decimal places
        
        mark1 = Double.parseDouble(mark1Input.getText()); //Assign user input in mark1Input text field to variable mark 1
        mark2 = Double.parseDouble(mark2Input.getText()); //Assign user input in mark2Input text field to variable mark 2
        mark3 = Double.parseDouble(mark3Input.getText()); //Assign user input in mark3Input text field to variable mark 3
        mark4 = Double.parseDouble(mark4Input.getText()); //Assign user input in mark4Input text field to variable mark 4
        
        average = (mark1 + mark2 + mark3 + mark4)/4; //Add all of the marks together and divide by four - calculates average
        
        roundedAverage = average*100; //Rounding algorithm to round the average to two decimal places
        roundedAverage = Math.round(roundedAverage);
        roundedAverage = roundedAverage/100;
        
        output.setText("Average: " +String.valueOf(roundedAverage)+ "%"); //Output the numerical value of the average to the text field "output"
        
    }//GEN-LAST:event_calculateButtonActionPerformed

    private void mark1InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark1InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark1InputActionPerformed

    private void outputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputActionPerformed

    private void mark4InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark4InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark4InputActionPerformed

    private void mark2InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mark2InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mark2InputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(averageCalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(averageCalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(averageCalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(averageCalculatorUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new averageCalculatorUi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton calculateButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mark1;
    private javax.swing.JTextField mark1Input;
    private javax.swing.JLabel mark2;
    private javax.swing.JTextField mark2Input;
    private javax.swing.JLabel mark3;
    private javax.swing.JTextField mark3Input;
    private javax.swing.JLabel mark4;
    private javax.swing.JTextField mark4Input;
    private javax.swing.JTextField output;
    private javax.swing.JLabel subtitle;
    // End of variables declaration//GEN-END:variables
}
